import { Project } from "@/types";

export const PROJECTS: Project[] = [
    {
        name: "Mock Data - Generate Realistic fake data",
        stack: "Next.js | Faker.js | TailwindCSS",
        description: "I built this platform to simplify the process of designing and generating mock data for developers, testers, and teams working on real-world applications. Whether you're building an app, testing APIs, or need sample datasets for your projects, this tool is here to make it fast, reliable, and fully customisable.The mock data generator currently supports 26 different data categories and allows you to create nearly 200+ unique types of data, catering to diverse application and testing needs. Currently supports generation of fake data in 43 different languages.",
        githubLink: "",
        websiteLink: "https://www.mock-data.com",
        category: "web",
        featured: true,
        techDescriptions: {
            "Next.js": "App router, API routes & SSR",
            "Faker.js": "200+ data types across 43 locales",
            "TailwindCSS": "UI layout & responsive design",
        },
    },
    {
        name: "DataForge - Through WebScrape workflow",
        stack: "Next.js | Puppeteer | Prisma | OpenAI",
        description: "A dataset creator for ML models through Web-scrape workflows. Allows users to create web-scraping workflows with various configuration to create web-scraping workflow to collect data for dataset. It has AI integration that allows AI to extract necessary selectors and data from website. Also has facilities to schedule the workflow to appropriate times using cron syntax. Currently can send the data through webhook. In future, In house dataset storage and marketplace for selling datasets will be implemented.",
        githubLink: "https://github.com/itsraghul/FlowBuilder",
        websiteLink: "https://flow-data-forge.vercel.app/",
        category: "web",
        featured: true,
        techDescriptions: {
            "Next.js": "Full-stack app with API routes",
            "Puppeteer": "Headless browser for web scraping",
            "Prisma": "Type-safe ORM for workflow storage",
            "OpenAI": "AI-powered CSS selector extraction",
        },
    },
    {
        name: "Hearty-Foods - Food delivery app",
        stack: "Next.js | MongoDB | Cloudinary | Paypal API",
        description: "Hearty Foods is a food order and delivery site build using NextJS. It has MongoDB for data storage and Material UI for styling.User can be able to order food and see their order history.Payment can be made with cash or through Paypal.The Admin(owner) can create new dishes and administer the orders made by the users and check the total collection and all the data. It was build using several apis like JSCookies, Cloudinary, JWToken and so on for various features.",
        githubLink: "https://github.com/itsraghul/hearty-foods",
        websiteLink: "https://hearty-foods.vercel.app/",
        category: "web",
        techDescriptions: {
            "Next.js": "Server-side rendering & routing",
            "MongoDB": "Menu items & order data storage",
            "Cloudinary": "Dish image upload & CDN delivery",
            "Paypal API": "Secure payment processing",
        },
    },
    {
        name: "MediNet - Decentralized Medical Network",
        stack: "Next.js | Ethereum | Web3 | IPFS",
        description: "A Decentralized Platform that provides Patient Record Management Services and Medical Community Network for Doctors. Platform allows patient to have control over their medical record. And doctors to form their own medical networks for better patient diagnosis. The files shared in the platform are done using IPFS.",
        githubLink: "https://github.com/itsraghul/medi-net",
        websiteLink: "https://medinet.vercel.app/",
        category: "blockchain",
        techDescriptions: {
            "Next.js": "Frontend app & patient dashboard",
            "Ethereum": "Smart contracts for record ownership",
            "Web3": "Wallet connection & contract calls",
            "IPFS": "Decentralized medical file storage",
        },
    },
    {
        name: "CampFund - Decentralized Funding Network",
        stack: "Next.js | Ethereum | Solidity | Azure",
        description: "An Open-Public Project Fund Raising Site. Uses Ethereum for exchange of funds. User can create their own project fund by deploying the smart contract instance with the help of this site. The Fund Raising Contract Factory have been deployed to Rinkeby Test Network. The Users need a Metamask Account and RinkebyEther to transfer and fund cryptocoins. A Project Fund manager can create a new request for projects and need the approval of contributors.All project changes are open and seen by the contributors which prevents embezzlement.Added Azure Chat bot for customer help.",
        githubLink: "https://github.com/itsraghul/camp-fund",
        websiteLink: "https://my-camp-fund.vercel.app/",
        category: "blockchain",
        techDescriptions: {
            "Next.js": "Campaign UI & contributor dashboard",
            "Ethereum": "Fund transfers via Rinkeby testnet",
            "Solidity": "Contract factory for each campaign",
            "Azure": "Azure Bot for customer support",
        },
    },
    {
        name: "RS Blockchain - A miniature blockchain",
        stack: "Javascript | Redis",
        description: "A miniature block chain built using Javascript. It uses redis pub-sub model for blockchain transaction and mining.",
        githubLink: "https://github.com/itsraghul/rs-blockchain/",
        websiteLink: "",
        category: "tools",
        techDescriptions: {
            "Javascript": "Core blockchain & mining logic",
            "Redis": "Pub-sub for peer-to-peer transactions",
        },
    },
    {
        name: "TriviaWebApp",
        stack: "Javascript | HTML | CSS",
        description: "A simple triva app that gives you random trivia quesitons. The highscores are stored in browser storage for user understanding.",
        githubLink: "https://github.com/itsraghul/TriviaWebApp",
        websiteLink: "https://trivia-web-app.vercel.app/",
        category: "web",
        techDescriptions: {
            "Javascript": "Quiz logic & score tracking",
            "HTML": "Semantic markup & accessibility",
            "CSS": "Styling & responsive layout",
        },
    },
    {
        name: "Cosmic Breakout- Endless Runner Mobile Game",
        stack: "GDevelop5",
        description: "A endless runner mobile game developed using GDevelop5.",
        githubLink: "https://github.com/itsraghul/CosmicBreakoutGameAndroid",
        websiteLink: "",
        category: "game",
        techDescriptions: {
            "GDevelop5": "No-code game engine for Android build",
        },
    },
    {
        name: "lockwarden — npm Supply-Chain Security CLI",
        stack: "TypeScript | Node.js | SARIF | SLSA Provenance",
        description:
            "A free, open-source, local-first CLI that audits what an npm dependency tree can execute — install scripts, native build hooks, AI-agent hooks, and IDE task files — and answers \"am I hit?\" in seconds during supply-chain incidents. Where traditional scanners ask \"is this package known-bad?\" (and lag behind attacks), lockwarden asks \"what can this tree execute, and what changed?\" — structural detection that works on day zero, before any advisory exists. Incident triage runs straight from the lockfile with no install or account; PR delta-scoring flags the execution surface a dependency bump introduced (new postinstall, added binding.gyp, 25x size jump); it scans vendored node_modules inside tarballs, zips, and Docker layers that registry-level scanners never see. Zero telemetry, zero backend — nothing leaves the machine, with an --offline mode that hard-fails on any network attempt for airgapped CI. 3 runtime dependencies (zero transitive) with custom tar and lockfile parsers, a unified resolution model across npm/yarn/pnpm lockfiles, SARIF output for the GitHub Security tab, and a fully automated SLSA-provenance release pipeline. TypeScript, 270+ tests, MIT.",
        githubLink: "https://github.com/itsraghul/lockwarden",
        websiteLink: "https://lockwarden.dev",
        category: "tools",
        featured: true,
        techDescriptions: {
            "TypeScript": "Core CLI, parsers & detection engine",
            "Node.js": "Lockfile-only npx runtime, zero install",
            "SARIF": "Findings into the GitHub Security tab",
            "SLSA Provenance": "Signed, automated release pipeline",
        },
    },
];
